openapi: 3.0.0
info:
  title: OpenAPI example
  description: "OpenAPI example"
  version: 1.0.0
servers:
- url: https://example.com/api/v1
paths:
  /user/{username}:
    get:
      operationId: getUserByName
      summary: Get user by user name
      parameters:
      - name: username
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        username:
          type: string
          example: user1
        email:
          type: string
          example: user1@example.com
        phone:
          type: string
          example: "000-0000-0000"